name: Testrun CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install Boost"
      run: sudo apt install libboost-all-dev
    - name: "Install other dependencies"
      run: |
        sudo apt install zsh bgpdump xz-utils
    - name: "Install everything"
      run: |
        echo Running install
        make install
